/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trypos2;

/**
 *
 * @author Jealian Abby Sulit
 */
public class pos extends javax.swing.JFrame {

    /**
     * Creates new form pos
     */
    public pos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        subTotal = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        subtotalField = new javax.swing.JTextField();
        discountField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        resetOrderButton = new javax.swing.JButton();
        removeOrderButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        changeLabel = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        paymentMethod = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        calcu = new javax.swing.JPanel();
        key6 = new javax.swing.JButton();
        key1 = new javax.swing.JButton();
        key2 = new javax.swing.JButton();
        payButton = new javax.swing.JButton();
        key9 = new javax.swing.JButton();
        key5 = new javax.swing.JButton();
        key4 = new javax.swing.JButton();
        key7 = new javax.swing.JButton();
        key8 = new javax.swing.JButton();
        key3 = new javax.swing.JButton();
        dotButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menu6 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        menu11 = new javax.swing.JButton();
        menu12 = new javax.swing.JButton();
        menu13 = new javax.swing.JButton();
        menu14 = new javax.swing.JButton();
        menu10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTable();
        barcodeField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(150, 119, 60));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 244));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subTotal.setBackground(new java.awt.Color(204, 204, 204));
        subTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        subTotal.setToolTipText("");
        subTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        totalLabel.setText("Total:");
        subTotal.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        subtotalLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        subtotalLabel.setText("SubTotal:");
        subTotal.add(subtotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        discountLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        discountLabel.setText("Discount:");
        subTotal.add(discountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        totalField.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        subTotal.add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, 30));

        subtotalField.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        subTotal.add(subtotalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 140, 30));

        discountField.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        subTotal.add(discountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, 30));

        jPanel2.add(subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 320, 210));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resetOrderButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        resetOrderButton.setText("Reset Order");
        resetOrderButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        resetOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetOrderButtonActionPerformed(evt);
            }
        });
        jPanel6.add(resetOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 160, 60));

        removeOrderButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        removeOrderButton.setText("Remove Order");
        removeOrderButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        removeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeOrderButtonActionPerformed(evt);
            }
        });
        jPanel6.add(removeOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 60));

        printButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        printButton.setText("Print Receipt");
        printButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        jPanel6.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 60));

        exitButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        exitButton.setText("Exit");
        exitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel6.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 160, 60));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 380, 180));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        jLabel4.setText("Method:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 20));

        amountLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        amountLabel.setText("Amount:");
        jPanel7.add(amountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jTextField5.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jPanel7.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, 30));

        changeLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        changeLabel.setText("Change:");
        jPanel7.add(changeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 20));

        jTextField6.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jPanel7.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 160, 30));

        paymentMethod.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        paymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "GCash", " ", " " }));
        jPanel7.add(paymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 160, 30));

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        jLabel7.setText("Payment");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 280, 380, 180));

        calcu.setBackground(new java.awt.Color(204, 204, 204));
        calcu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        calcu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        key6.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key6.setText("6");
        key6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key6ActionPerformed(evt);
            }
        });
        calcu.add(key6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, 70));

        key1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key1.setText("1");
        key1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key1ActionPerformed(evt);
            }
        });
        calcu.add(key1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 70));

        key2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key2.setText("2");
        key2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key2ActionPerformed(evt);
            }
        });
        calcu.add(key2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 60, 70));

        payButton.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        payButton.setText("PAY");
        payButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });
        calcu.add(payButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 110, 150));

        key9.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key9.setText("9");
        key9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key9ActionPerformed(evt);
            }
        });
        calcu.add(key9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 60, 70));

        key5.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key5.setText("5");
        key5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key5ActionPerformed(evt);
            }
        });
        calcu.add(key5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 60, 70));

        key4.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key4.setText("4");
        key4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key4ActionPerformed(evt);
            }
        });
        calcu.add(key4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, 70));

        key7.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key7.setText("7");
        key7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key7ActionPerformed(evt);
            }
        });
        calcu.add(key7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, 70));

        key8.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key8.setText("8");
        key8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key8ActionPerformed(evt);
            }
        });
        calcu.add(key8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 60, 70));

        key3.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key3.setText("3");
        key3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key3ActionPerformed(evt);
            }
        });
        calcu.add(key3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 60, 70));

        dotButton.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        dotButton.setText(".");
        dotButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonActionPerformed(evt);
            }
        });
        calcu.add(dotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 50, 70));

        clearButton.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        clearButton.setText("C");
        clearButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        calcu.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 50, 70));

        jPanel2.add(calcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 470, 380, 280));

        jPanel1.setBackground(new java.awt.Color(216, 216, 173));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starbucks-logo1-removebg-preview.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STARBARACKS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 120));

        menu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iced white mocha.png"))); // NOI18N
        menu6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 170, 230));
        jPanel1.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 20, 540));

        menu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/caffe vanilla frappe.png"))); // NOI18N
        menu11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(menu11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, 230));

        menu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iced caffe mocha.png"))); // NOI18N
        menu12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(menu12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 170, 230));

        menu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/java chip frappucino.png"))); // NOI18N
        menu13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(menu13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 170, 230));

        menu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mocha cookie crumble.png"))); // NOI18N
        menu14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(menu14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 170, 230));

        menu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/strawberry creme frappuccino.png"))); // NOI18N
        menu10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(menu10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 170, 230));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 660));

        receipt.setBackground(new java.awt.Color(232, 232, 232));
        receipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantity", "Item", "Price"
            }
        ));
        jScrollPane1.setViewportView(receipt);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 320, 380));

        barcodeField.setBackground(new java.awt.Color(232, 232, 232));
        barcodeField.setFont(new java.awt.Font("Code39", 0, 48)); // NOI18N
        barcodeField.setText("AGSDHGHASDJHSAFHAGFHGFHGA");
        barcodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeFieldActionPerformed(evt);
            }
        });
        jPanel2.add(barcodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 320, 60));

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 3, 45)); // NOI18N
        jLabel2.setText("POINT OF SALES SYSTEM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void key6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key6ActionPerformed

    private void key1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key1ActionPerformed

    private void key2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key2ActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payButtonActionPerformed

    private void key9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key9ActionPerformed

    private void key5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key5ActionPerformed

    private void key4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key4ActionPerformed

    private void key7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key7ActionPerformed

    private void key8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key8ActionPerformed

    private void key3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key3ActionPerformed

    private void dotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dotButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void barcodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodeFieldActionPerformed

    private void resetOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetOrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetOrderButtonActionPerformed

    private void removeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeOrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeOrderButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField barcodeField;
    private javax.swing.JPanel calcu;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField discountField;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton key1;
    private javax.swing.JButton key2;
    private javax.swing.JButton key3;
    private javax.swing.JButton key4;
    private javax.swing.JButton key5;
    private javax.swing.JButton key6;
    private javax.swing.JButton key7;
    private javax.swing.JButton key8;
    private javax.swing.JButton key9;
    private javax.swing.JButton menu10;
    private javax.swing.JButton menu11;
    private javax.swing.JButton menu12;
    private javax.swing.JButton menu13;
    private javax.swing.JButton menu14;
    private javax.swing.JButton menu6;
    private javax.swing.JButton payButton;
    private javax.swing.JComboBox<String> paymentMethod;
    private javax.swing.JButton printButton;
    private javax.swing.JTable receipt;
    private javax.swing.JButton removeOrderButton;
    private javax.swing.JButton resetOrderButton;
    private javax.swing.JPanel subTotal;
    private javax.swing.JTextField subtotalField;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JTextField totalField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
