/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pointofsalessystem;


import java.text.MessageFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import pointofsalessystem.Dashboard;

/**
 *
 * @author Jealian Abby Sulit
 */
public class pos extends javax.swing.JFrame {

    final String format = "\n%-16s \t%-6d \t%.2f";
    
    ArrayList<String> menuBought = new ArrayList();
    ArrayList<String> menu = new ArrayList<>();
    ArrayList<String> orders = new ArrayList<>();
    ArrayList<MouseListener> listeners = new ArrayList<>();
    
   
    int queueNumber;
    
    
    public pos() {
        initComponents();
        
       
        
        
    
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        subTotal = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        subtotalField = new javax.swing.JTextField();
        taxField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        resetOrderButton = new javax.swing.JButton();
        removeOrderButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        changeLabel = new javax.swing.JLabel();
        changeField = new javax.swing.JTextField();
        paymentMethod = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        calcu = new javax.swing.JPanel();
        key6 = new javax.swing.JButton();
        key1 = new javax.swing.JButton();
        key2 = new javax.swing.JButton();
        payButton = new javax.swing.JButton();
        key9 = new javax.swing.JButton();
        key5 = new javax.swing.JButton();
        key4 = new javax.swing.JButton();
        key7 = new javax.swing.JButton();
        key8 = new javax.swing.JButton();
        key3 = new javax.swing.JButton();
        key0 = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barcodeField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        macadamia = new javax.swing.JButton();
        vscBrew = new javax.swing.JButton();
        americano = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        javaChip = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mochaFrap = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mochaCookie = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        matcha = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pineapp = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        straw = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        summerBlend = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        dragon = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        chocoCrois = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cloudck = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        bagel = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        hamCrois = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lemonLoaf = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cookie = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(150, 119, 60));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 244));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subTotal.setBackground(new java.awt.Color(204, 204, 204));
        subTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        subTotal.setToolTipText("");
        subTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        totalLabel.setText("Total:");
        subTotal.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        subtotalLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        subtotalLabel.setText("SubTotal:");
        subTotal.add(subtotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        discountLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        discountLabel.setText("Tax:");
        subTotal.add(discountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        totalField.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        subTotal.add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, 30));

        subtotalField.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        subTotal.add(subtotalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 140, 30));

        taxField.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        subTotal.add(taxField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, 30));

        jPanel2.add(subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, 320, 200));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resetOrderButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        resetOrderButton.setText("Reset Order");
        resetOrderButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        resetOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetOrderButtonActionPerformed(evt);
            }
        });
        jPanel6.add(resetOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 160, 60));

        removeOrderButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        removeOrderButton.setText("Remove Order");
        removeOrderButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        removeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeOrderButtonActionPerformed(evt);
            }
        });
        jPanel6.add(removeOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 60));

        printButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        printButton.setText("Print Receipt");
        printButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        jPanel6.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 60));

        exitButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        exitButton.setText("Exit");
        exitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel6.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 160, 60));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, 380, 180));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        jLabel4.setText("Method:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 20));

        amountLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        amountLabel.setText("Amount:");
        jPanel7.add(amountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        amountField.setEditable(false);
        amountField.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jPanel7.add(amountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, 30));

        changeLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        changeLabel.setText("Change:");
        jPanel7.add(changeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 20));

        changeField.setEditable(false);
        changeField.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jPanel7.add(changeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 160, 30));

        paymentMethod.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        paymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "GCash", " ", " " }));
        jPanel7.add(paymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 160, 30));

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        jLabel7.setText("Payment");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 310, 380, 180));

        calcu.setBackground(new java.awt.Color(204, 204, 204));
        calcu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        calcu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        key6.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key6.setText("6");
        key6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key6ActionPerformed(evt);
            }
        });
        calcu.add(key6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, 70));

        key1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key1.setText("1");
        key1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key1ActionPerformed(evt);
            }
        });
        calcu.add(key1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 70));

        key2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key2.setText("2");
        key2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key2ActionPerformed(evt);
            }
        });
        calcu.add(key2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 60, 70));

        payButton.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        payButton.setText("PAY");
        payButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        payButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payButtonMouseClicked(evt);
            }
        });
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });
        calcu.add(payButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 110, 150));

        key9.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key9.setText("9");
        key9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key9ActionPerformed(evt);
            }
        });
        calcu.add(key9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 60, 70));

        key5.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key5.setText("5");
        key5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key5ActionPerformed(evt);
            }
        });
        calcu.add(key5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 60, 70));

        key4.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key4.setText("4");
        key4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key4ActionPerformed(evt);
            }
        });
        calcu.add(key4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, 70));

        key7.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key7.setText("7");
        key7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key7ActionPerformed(evt);
            }
        });
        calcu.add(key7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, 70));

        key8.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key8.setText("8");
        key8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key8ActionPerformed(evt);
            }
        });
        calcu.add(key8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 60, 70));

        key3.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key3.setText("3");
        key3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key3ActionPerformed(evt);
            }
        });
        calcu.add(key3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 60, 70));

        key0.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        key0.setText("0");
        key0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        key0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key0ActionPerformed(evt);
            }
        });
        calcu.add(key0, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 50, 70));

        clearButton.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        clearButton.setText("C");
        clearButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        calcu.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 50, 70));

        jPanel2.add(calcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 500, 380, 280));

        receipt.setBackground(new java.awt.Color(232, 232, 232));
        receipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantity", "Item", "Price"
            }
        ));
        jScrollPane1.setViewportView(receipt);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 320, 390));

        jPanel3.setBackground(new java.awt.Color(51, 102, 0));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SBRKS MENU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 100));

        barcodeField.setBackground(new java.awt.Color(232, 232, 232));
        barcodeField.setFont(new java.awt.Font("Code39", 0, 36)); // NOI18N
        barcodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeFieldActionPerformed(evt);
            }
        });
        jPanel2.add(barcodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 320, 60));

        jPanel1.setBackground(new java.awt.Color(170, 170, 116));
        jPanel1.setPreferredSize(new java.awt.Dimension(560, 2000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        macadamia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Macadamia cream cold brew.png"))); // NOI18N
        macadamia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                macadamiaActionPerformed(evt);
            }
        });
        jPanel1.add(macadamia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 170, 160));

        vscBrew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vanilla sweet cream cold brew.png"))); // NOI18N
        vscBrew.setText("Sweet Cream Cold Brew");
        vscBrew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vscBrewActionPerformed(evt);
            }
        });
        jPanel1.add(vscBrew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 160));

        americano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iced caffe americano.png"))); // NOI18N
        americano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                americanoActionPerformed(evt);
            }
        });
        jPanel1.add(americano, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 170, 160));

        jPanel4.setBackground(new java.awt.Color(255, 255, 229));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("P230.00");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText(" Sweet Cream Cold Brew");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 26));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 229));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Iced Caffe Americano");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 26));

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("P150.00");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 170, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 229));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText(" Macadamia Cold Brew");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 26));

        jLabel10.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("P240.00");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 170, -1));

        javaChip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/java chip frappe.png"))); // NOI18N
        javaChip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaChipActionPerformed(evt);
            }
        });
        jPanel1.add(javaChip, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 170, 160));

        jPanel9.setBackground(new java.awt.Color(255, 255, 229));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Java Chip Frappuccino");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 26));

        jLabel12.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("P170.00");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 170, -1));

        mochaFrap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mocha frappe.png"))); // NOI18N
        mochaFrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochaFrapActionPerformed(evt);
            }
        });
        jPanel1.add(mochaFrap, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 170, 160));

        jPanel10.setBackground(new java.awt.Color(255, 255, 229));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Mocha Frappuccino");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 26));

        jLabel14.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("P150.00");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 170, -1));

        mochaCookie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mochacookiecrumblefrapp.png"))); // NOI18N
        mochaCookie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochaCookieActionPerformed(evt);
            }
        });
        jPanel1.add(mochaCookie, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 170, 160));

        jPanel11.setBackground(new java.awt.Color(255, 255, 229));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Mocha Cookie Crumble ");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 26));

        jLabel16.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("P190.00");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 170, -1));

        matcha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/matcha creme frappe.png"))); // NOI18N
        matcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchaActionPerformed(evt);
            }
        });
        jPanel1.add(matcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 170, 160));

        jPanel12.setBackground(new java.awt.Color(255, 255, 229));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Macha Creme Frappe");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 26));

        jLabel18.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("P180.00");
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 170, -1));

        pineapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/frozen pineapple passionfruit.png"))); // NOI18N
        pineapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pineappActionPerformed(evt);
            }
        });
        jPanel1.add(pineapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 170, 160));

        jPanel13.setBackground(new java.awt.Color(255, 255, 229));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Pineapple Passionfruit");
        jPanel13.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 26));

        jLabel20.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("P200.00");
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 690, 170, -1));

        straw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/strawberry acai lemonade.png"))); // NOI18N
        straw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawActionPerformed(evt);
            }
        });
        jPanel1.add(straw, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 170, 160));

        jPanel14.setBackground(new java.awt.Color(255, 255, 229));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Strawberry Lemonade");
        jPanel14.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 26));

        jLabel22.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("P230.00");
        jPanel14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 690, 170, -1));

        summerBlend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/summer berry lemonade.png"))); // NOI18N
        summerBlend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summerBlendActionPerformed(evt);
            }
        });
        jPanel1.add(summerBlend, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 780, 170, 160));

        jPanel15.setBackground(new java.awt.Color(255, 255, 229));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Summer Berry Lemon");
        jPanel15.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 26));

        jLabel24.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("P220.00");
        jPanel15.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 940, 170, -1));

        dragon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon drink.png"))); // NOI18N
        dragon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dragonActionPerformed(evt);
            }
        });
        jPanel1.add(dragon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 780, 170, 160));

        jPanel16.setBackground(new java.awt.Color(255, 255, 229));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Dragon Drink");
        jPanel16.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, 26));

        jLabel26.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("P230.00");
        jPanel16.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 940, 170, -1));

        chocoCrois.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/choco croissant.png"))); // NOI18N
        chocoCrois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocoCroisActionPerformed(evt);
            }
        });
        jPanel1.add(chocoCrois, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 780, 170, 160));

        jPanel17.setBackground(new java.awt.Color(255, 255, 229));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Choco Croissant");
        jPanel17.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 26));

        jLabel28.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("P110.00");
        jPanel17.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 940, 170, -1));

        cloudck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pineapple cloud cake.png"))); // NOI18N
        cloudck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cloudckActionPerformed(evt);
            }
        });
        jPanel1.add(cloudck, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1030, 170, 160));

        jPanel18.setBackground(new java.awt.Color(255, 255, 229));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Pineapple Cloud Cake");
        jPanel18.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 26));

        jLabel30.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("P140.00");
        jPanel18.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1190, 170, -1));

        bagel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bagel.png"))); // NOI18N
        bagel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagelActionPerformed(evt);
            }
        });
        jPanel1.add(bagel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1030, 170, 160));

        jPanel19.setBackground(new java.awt.Color(255, 255, 229));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Bagel");
        jPanel19.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 26));

        jLabel32.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("P60.00");
        jPanel19.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1190, 170, -1));

        hamCrois.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ham n swiss croissnt.png"))); // NOI18N
        hamCrois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamCroisActionPerformed(evt);
            }
        });
        jPanel1.add(hamCrois, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1030, 170, 160));

        jPanel20.setBackground(new java.awt.Color(255, 255, 229));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("Ham and Swiss Croissant");
        jPanel20.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 26));

        jLabel34.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("P90.00");
        jPanel20.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1190, 170, -1));

        lemonLoaf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iced lemon loaf.png"))); // NOI18N
        lemonLoaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemonLoafActionPerformed(evt);
            }
        });
        jPanel1.add(lemonLoaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1280, 170, 160));

        jPanel21.setBackground(new java.awt.Color(255, 255, 229));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("Iced Lemon Loaf");
        jPanel21.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 26));

        jLabel36.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("P120.00");
        jPanel21.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1440, 170, -1));

        cookie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chocolate cookie chip.png"))); // NOI18N
        cookie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookieActionPerformed(evt);
            }
        });
        jPanel1.add(cookie, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1280, 170, 160));

        jPanel22.setBackground(new java.awt.Color(255, 255, 229));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Montserrat SemiBold", 1, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 51, 51));
        jLabel37.setText("Chocolate Cookie Chip");
        jPanel22.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 26));

        jLabel38.setFont(new java.awt.Font("Montserrat SemiBold", 3, 10)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 51, 51));
        jLabel38.setText("P70.00");
        jPanel22.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 26));

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1440, 170, -1));

        jScrollPane2.setViewportView(jPanel1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 600, 560));

        jPanel23.setBackground(new java.awt.Color(51, 102, 0));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starbucks-logo1-removebg-preview.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("STARBARACKS ORDER SYSTEM");

        homeButton.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/house-black-silhouette-without-door.png"))); // NOI18N
        homeButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(homeButton)
                .addGap(18, 18, 18))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeButton)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//=========================Function=============================

   
        
    
    
    //Get quantity of orders
    public void getQuantity(double a, String b){
        //init values
        final int MINIMUM_ORDER_VALUE=0;
        final int MAXIMUM_ORDER_VALUE=30;
        final int ORDER_INCREMENT =1;
        
        //Create a spinner object
        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(MINIMUM_ORDER_VALUE,MINIMUM_ORDER_VALUE,MAXIMUM_ORDER_VALUE,ORDER_INCREMENT);
        JSpinner spinner = new JSpinner(spinnerModel);
        JSpinner.DefaultEditor editor = (JSpinner.DefaultEditor) spinner.getEditor();
        JTextField txt = editor.getTextField();
        txt.setEditable(true);
        
        //Pop-up
        JOptionPane.showMessageDialog(null, spinner, "Quantity" , JOptionPane.INFORMATION_MESSAGE);
        int spinnerValue = (Integer) spinner.getValue();
        double price = a;
        
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        
            
        
        
        if(spinnerValue>0){
        double cost = spinnerValue*price;
        model.addRow(new Object[]{b, spinnerValue, cost});
        ItemCost();
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Message", "Invalid quantity", JOptionPane.INFORMATION_MESSAGE); 
        }
    }
    
    public void ItemCost(){
        double total = 0;
        for  (int i=0; i<receipt.getRowCount(); i++)
        {
            total = total + Double.parseDouble(receipt.getValueAt(i,2).toString());
        }
        subtotalField.setText(Double.toString(total));
        double total1 = Double.parseDouble(subtotalField.getText());
        
        //tax
        double tax = (total1 *2.4)/100;
        String fTax = String.format("P %.2f", tax);
        taxField.setText((fTax));
        
        ///subtotal
        String fsubTotal = String.format("P %.2f", total1);
        subtotalField.setText(fsubTotal);
        
        //total
        String fTotal = String.format("P %.2f", total1 + tax);
        totalField.setText(fTotal);
        
        String barCode = String.format("Total is %.2f", total1 + tax);
        barcodeField.setText(barCode);
    }

//=========================Function Change=============================
    public void Change(){
        double  total = 0;
        double tax = 2.4;
        double amount = Double.parseDouble(amountField.getText());
        
         for  (int i=0; i<receipt.getRowCount(); i++)
        {
            total = total + Double.parseDouble(receipt.getValueAt(i,2).toString());
        }
        
         double fTax  = (total *tax)/100;
         double fChange = (amount - (total + fTax ));
         
         String change = String.format("P %.2f", fChange );
         changeField.setText(change);
    }

//==========================Key Functions==================================
    private void key6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key6ActionPerformed
        String number = amountField.getText();
        
        if (number ==""){
            amountField.setText(key6.getText());
        }
        else
        {
            number = amountField.getText() + key6.getText();
            amountField.setText(number);
        }
        
    }//GEN-LAST:event_key6ActionPerformed

    private void key1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key1ActionPerformed
        String number = amountField.getText();
        
        if (number ==""){
            amountField.setText(key1.getText());
        }
        else
        {
            number = amountField.getText() + key1.getText();
            amountField.setText(number);
        }
        
    }//GEN-LAST:event_key1ActionPerformed

    private void key2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key2ActionPerformed
        String number = amountField.getText();
        
        if (number ==""){
            amountField.setText(key2.getText());
        }
        else
        {
            number = amountField.getText() + key2.getText();
            amountField.setText(number);
        }
    }//GEN-LAST:event_key2ActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
       if (paymentMethod.getSelectedItem().equals("Cash")){
           Change();
           String total = totalField.getText();
           
           //get Date and Time
           Date currentDate = new Date();
           SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm a");
           SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
           
           OrderHistory.addRowToHistory(new Object[]{
           dateFormat.format(currentDate),timeFormat.format(currentDate),receipt.getValueAt(0, 0), total
           });
       }
       else
       {
           changeField.setText("");
           amountField.setText("");
       }
       

    }//GEN-LAST:event_payButtonActionPerformed

    private void key9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key9ActionPerformed
      String number = amountField.getText();
        
        if (number ==""){
            amountField.setText(key9.getText());
        }
        else
        {
            number = amountField.getText() + key9.getText();
            amountField.setText(number);
        }
    }//GEN-LAST:event_key9ActionPerformed

    private void key5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key5ActionPerformed
        String number = amountField.getText();
        
        if (number ==""){
            amountField.setText(key5.getText());
        }
        else
        {
            number = amountField.getText() + key5.getText();
            amountField.setText(number);
        }
    }//GEN-LAST:event_key5ActionPerformed

    private void key4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key4ActionPerformed
        String number = amountField.getText();
        
        if (number ==""){
            amountField.setText(key4.getText());
        }
        else
        {
            number = amountField.getText() + key4.getText();
            amountField.setText(number);
        }
    }//GEN-LAST:event_key4ActionPerformed

    private void key7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key7ActionPerformed
        String number = amountField.getText();
        
        if (number ==""){
            amountField.setText(key7.getText());
        }
        else
        {
            number = amountField.getText() + key7.getText();
            amountField.setText(number);
        }
    }//GEN-LAST:event_key7ActionPerformed

    private void key8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key8ActionPerformed
        String number = amountField.getText();
        
        if (number ==""){
            amountField.setText(key8.getText());
        }
        else
        {
            number = amountField.getText() + key8.getText();
            amountField.setText(number);
        }
    }//GEN-LAST:event_key8ActionPerformed

    private void key3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key3ActionPerformed
        String number = amountField.getText();
        
        if (number ==""){
            amountField.setText(key3.getText());
        }
        else
        {
            number = amountField.getText() + key3.getText();
            amountField.setText(number);
        }
    }//GEN-LAST:event_key3ActionPerformed

    private void key0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key0ActionPerformed
        String number = amountField.getText();
        
        if (number ==""){
            amountField.setText(key0.getText());
        }
        else
        {
            number = amountField.getText() + key0.getText();
            amountField.setText(number);
        }
    }//GEN-LAST:event_key0ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        amountField.setText("");
        changeField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void barcodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodeFieldActionPerformed

    private void resetOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetOrderButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        model.setRowCount(0);
        changeField.setText("");
        amountField.setText("");
        taxField.setText("");
        subtotalField.setText("");
        totalField.setText("");
        barcodeField.setText("");

    }//GEN-LAST:event_resetOrderButtonActionPerformed

    private void removeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeOrderButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        
        int remove = receipt.getSelectedRow();
        if(remove>=0){
            model.removeRow(remove);
        }
        
        ItemCost();
        
        if (paymentMethod.getSelectedItem().equals("Cash")){
           Change();
       }
       else
       {
           changeField.setText("");
           amountField.setText("");
       }
 
    }//GEN-LAST:event_removeOrderButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
       MessageFormat header = new MessageFormat("Printing in progress");
       MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
       try
       {
           receipt.print(JTable.PrintMode.NORMAL, header, footer);
       }
       catch (java.awt.print.PrinterException e)
               {
                   System.err.format("No printer found", e.getMessage());
               }
    }//GEN-LAST:event_printButtonActionPerformed

    private JFrame frame ;  
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        frame = new JFrame("Program Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit", "Starbaracks", JOptionPane. YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    
    }//GEN-LAST:event_exitButtonActionPerformed

    private void vscBrewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vscBrewActionPerformed
        String name = "Sweet Cream Cold Brew";
        double price = 230.00;
        getQuantity(price, name);
    }//GEN-LAST:event_vscBrewActionPerformed

    private void javaChipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaChipActionPerformed
        String name = "Java Chip Frappuccino";
        double price = 170.00;
        getQuantity(price, name);
    }//GEN-LAST:event_javaChipActionPerformed

    private void matchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchaActionPerformed
        String name = "Macha Cream Frappe";
        double price = 180.00;
        getQuantity(price, name);
        
    }//GEN-LAST:event_matchaActionPerformed

    private void summerBlendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summerBlendActionPerformed
        String name = "Summer Berry Lemon";
        double price = 220.00;
        getQuantity(price, name);
    }//GEN-LAST:event_summerBlendActionPerformed

    private void cloudckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cloudckActionPerformed
        String name = "Pineapple Cloud Cake";
        double price = 140.00;
        getQuantity(price, name);
    }//GEN-LAST:event_cloudckActionPerformed

    private void lemonLoafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemonLoafActionPerformed
        String name = "Iced Lemon Loaf";
        double price = 120.00;
        getQuantity(price, name);
    }//GEN-LAST:event_lemonLoafActionPerformed

    private void cookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookieActionPerformed
        String name = "Chocolate Cookie Chip";
        double price = 70.00;
        getQuantity(price, name);
    }//GEN-LAST:event_cookieActionPerformed

    private void americanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_americanoActionPerformed
        String name = "Iced Caffe Americano";
        double price = 150.00;
        getQuantity(price, name);
    }//GEN-LAST:event_americanoActionPerformed

    private void macadamiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_macadamiaActionPerformed
        String name = "Macadamia Cold Brew";
        double price = 240.00;
        getQuantity(price, name);
    }//GEN-LAST:event_macadamiaActionPerformed

    private void mochaFrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochaFrapActionPerformed
        String name = "Mocha Frappuccino";
        double price = 150.00;
        getQuantity(price, name);
    }//GEN-LAST:event_mochaFrapActionPerformed

    private void mochaCookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochaCookieActionPerformed
        String name = "Mocha Cookie Crumble";
        double price = 190.00;
        getQuantity(price, name);
    }//GEN-LAST:event_mochaCookieActionPerformed

    private void pineappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pineappActionPerformed
        String name = "Pineapple Passionfruit";
        double price = 200.00;
        getQuantity(price, name);
    }//GEN-LAST:event_pineappActionPerformed

    private void strawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawActionPerformed
        String name = "Strawberry Lemonade";
        double price = 230.00;
        getQuantity(price, name);
    }//GEN-LAST:event_strawActionPerformed

    private void dragonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dragonActionPerformed
        String name = "Dragon Drink";
        double price = 230.00;
        getQuantity(price, name);
    }//GEN-LAST:event_dragonActionPerformed

    private void chocoCroisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocoCroisActionPerformed
        String name = "Choco Croissant";
        double price = 110.00;
        getQuantity(price, name);
    }//GEN-LAST:event_chocoCroisActionPerformed

    private void bagelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagelActionPerformed
        String name = "Bagel";
        double price = 120.00;
        getQuantity(price, name);
    }//GEN-LAST:event_bagelActionPerformed

    private void hamCroisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamCroisActionPerformed
        String name = "Ham and Swiss Croissant";
        double price = 90.00;
        getQuantity(price, name);
    }//GEN-LAST:event_hamCroisActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame1 = new Dashboard();
                frame1.setLocationRelativeTo(null);
                frame1.setResizable(false);
                frame1.setVisible(true);

            }
        });
    }//GEN-LAST:event_homeButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void payButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_payButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame pFrame = new pos();
                pFrame.setLocationRelativeTo(null);
                pFrame.setResizable(false);
                pFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton americano;
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JButton bagel;
    private javax.swing.JTextField barcodeField;
    private javax.swing.JPanel calcu;
    private javax.swing.JTextField changeField;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JButton chocoCrois;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton cloudck;
    private javax.swing.JButton cookie;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JButton dragon;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton hamCrois;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton javaChip;
    private javax.swing.JButton key0;
    private javax.swing.JButton key1;
    private javax.swing.JButton key2;
    private javax.swing.JButton key3;
    private javax.swing.JButton key4;
    private javax.swing.JButton key5;
    private javax.swing.JButton key6;
    private javax.swing.JButton key7;
    private javax.swing.JButton key8;
    private javax.swing.JButton key9;
    private javax.swing.JButton lemonLoaf;
    private javax.swing.JButton macadamia;
    private javax.swing.JButton matcha;
    private javax.swing.JButton mochaCookie;
    private javax.swing.JButton mochaFrap;
    private javax.swing.JButton payButton;
    private javax.swing.JComboBox<String> paymentMethod;
    private javax.swing.JButton pineapp;
    private javax.swing.JButton printButton;
    private javax.swing.JTable receipt;
    private javax.swing.JButton removeOrderButton;
    private javax.swing.JButton resetOrderButton;
    private javax.swing.JButton straw;
    private javax.swing.JPanel subTotal;
    private javax.swing.JTextField subtotalField;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JButton summerBlend;
    private javax.swing.JTextField taxField;
    private javax.swing.JTextField totalField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton vscBrew;
    // End of variables declaration//GEN-END:variables
}
